export const portfolioInfo = [
	{
		id: 1,
		image: 'https://i.postimg.cc/c4T1Yrkr/1.png',
		title: 'MERN Calendar',
		github: 'https://github.com/Skierhy/MERN-Calendar',
		demo: 'https://mern-calendar-skierhy.netlify.app/',
	},
	{
		id: 2,
		image: 'https://i.postimg.cc/WzWKdz6H/1.png',
		title: 'Mi portafolio',
		github: 'https://github.com/Skierhy/skierhy',
		demo: 'https://skierhy.github.io/skierhy/',
	},
	{
		id: 3,
		image: 'https://i.postimg.cc/J4YjrhmC/Captura-de-pantalla-2022-12-21-235447.png',
		title: 'Backend del calendario MERN',
		github: 'https://github.com/Skierhy/calendar-backend',
		demo: '',
	},
	{
		id: 4,
		image: 'https://i.postimg.cc/hvyw4WMP/1.png',
		title: 'journal App',
		github: 'https://github.com/Skierhy/journal-app',
		demo: 'https://journal-app-skierhy.netlify.app/',
	},
	{
		id: 5,
		image: 'https://i.postimg.cc/QCFtdssf/1.png',
		title: 'Heroes SPA App',
		github: 'https://github.com/Skierhy/heroes-spa-app',
		demo: 'https://heroes-spa-skierhy.netlify.app/marvel',
	},
	{
		id: 6,
		image: 'https://i.postimg.cc/s2f32y45/1.png',
		title: 'Gif Expert App',
		github: 'https://github.com/Skierhy/Gif-Expert-App',
		demo: "https://gif's-react-skierhy.netlify.app/",
	},
	{
		id: 7,
		image: 'https://i.postimg.cc/L6gTrpt6/1.png',
		title: 'Black Jack',
		github: 'https://github.com/Skierhy/Curso-de-JavaScript',
		demo: 'https://black-jack-skierhy.netlify.app/',
	},
	{
		id: 8,
		image: 'https://i.postimg.cc/QtZSqn9x/2.png',
		title: 'Países App',
		github: 'https://github.com/Skierhy/PaisesApp',
		demo: 'https://paises-app-skierhy.netlify.app/',
	},
	{
		id: 9,
		image: 'https://i.postimg.cc/bJ0Sfm6J/1.png',
		title: 'App Gifs Angular',
		github: 'https://github.com/Skierhy/App-Gifs-angular',
		demo: 'https://app-gifs-angular-skierhy.netlify.app/',
	},
];
