export const portfolioInfo = [
	{
		id: 1,
		image: 'https://i.postimg.cc/gkzKc5Z8/Captura-de-pantalla-2022-12-21-235255.png',
		title: 'MERN-Calendar',
		github: 'https://github.com/Skierhy/MERN-Calendar',
		demo: 'https://calendar-skierhy.netlify.app',
	},
	{
		id: 2,
		image: 'https://i.postimg.cc/y8WXcZnN/Captura-de-pantalla-2022-12-21-235348.png',
		title: 'Mi portafolio',
		github: 'https://github.com/Skierhy/skierhy',
		demo: 'https://skierhy.github.io/skierhy/',
	},
	{
		id: 3,
		image: 'https://i.postimg.cc/J4YjrhmC/Captura-de-pantalla-2022-12-21-235447.png',
		title: 'Backend del calendario MERN',
		github: 'https://github.com/Skierhy/calendar-backend',
		demo: '',
	},
	{
		id: 4,
		image: 'https://i.postimg.cc/T27KmHsr/Captura-de-pantalla-2022-12-21-235635.png',
		title: 'Journal App',
		github: 'https://github.com/Skierhy/journal-app',
		demo: '',
	},
	{
		id: 5,
		image: 'https://i.postimg.cc/3J0xGrmT/Captura-de-pantalla-2022-12-21-235727.png',
		title: 'Heroes App',
		github: 'https://github.com/Skierhy/heroes-spa-app',
		demo: '',
	},
	{
		id: 6,
		image: 'https://i.postimg.cc/pXBRz9r3/Captura-de-pantalla-2022-12-22-000135.png',
		title: 'Gif Expert App',
		github: 'https://github.com/Skierhy/Gif-Expert-App',
		demo: '',
	},
	{
		id: 7,
		image: 'https://i.postimg.cc/8zBDd7Cq/Captura-de-pantalla-2022-12-21-235921.png',
		title: 'Países App',
		github: 'https://github.com/Skierhy/PaisesApp',
		demo: '',
	},
	{
		id: 8,
		image: 'https://i.postimg.cc/76QqCjLh/Captura-de-pantalla-2022-12-21-235819.png',
		title: 'App Gifs angular',
		github: 'https://github.com/Skierhy/App-Gifs-angular',
		demo: '',
	},
	{
		id: 9,
		image: 'https://i.postimg.cc/gcMK45CS/1.jpg',
		title: 'Blog de café',
		github: 'https://github.com/Skierhy/blog-de-cafe',
		demo: '',
	},
];
